export const DOCS_CATEGORY = {
  'default ': 'default ',
  threejs: 'threejs',
  'accordion ': 'accordion ',
  'form ': 'form ',
  'sparkles ': 'sparkles ',
  Swapy: 'Swapy',
  'Color Picker': 'Color Picker',
  'carousel ': 'carousel ',
  creative: 'creative',
  'modal/drawer': 'modal/drawer',
  animation: 'animation',
  'text animation': 'text animation',
  scroll: 'scroll',
  grid: 'grid',
  marquee: 'marquee',
  'clip-path': 'clip-path',
  card: 'card',
  tab: 'tab',
} as const;
