export const DOCS_CATEGORY_GROUP = {
  Layout: 'Layout',
  Navigation: 'Navigation',
  Disclosure: 'Disclosure',
  Overlays: 'Overlays',
  Forms: 'Forms',
  DataDisplay: 'Cards & Highlights',
  MediaGalleries: 'Media & Galleries',
  AnimationMotion: 'Animation & Motion',
  VisualEffects: 'Visual Effects',
  Visual3D: '3D & Visuals',
  Utilities: 'Utilities',
} as const;

export const DOCS_CATEGORY_KEY = {
  'liquid-glass': 'liquid-glass',
  'color-picker': 'color-picker',
  buttons: 'buttons',
  noise: 'noise',
  globe: 'globe',
  footers: 'footers',
  'responsive-header': 'responsive-header',
  'buy-me-coffee': 'buy-me-coffee',
  swapy: 'swapy',
  'drag-items': 'drag-items',
  'image-ripple-effect': 'image-ripple-effect',
  'r3f-blob': 'r3f-blob',
  'mesh-gradients': 'mesh-gradients',
  'blur-vignette': 'blur-vignette',
  'motion-number': 'motion-number',
  'liquid-button': 'liquid-button',
  'liquid-gradient': 'liquid-gradient',
  'range-slider': 'range-slider',
  password: 'password',
  'tags-input': 'tags-input',
  'phone-input': 'phone-input',
  'datetime-picker': 'datetime-picker',
  'multi-selector': 'multi-selector',
  'file-upload': 'file-upload',
  'clip-path': 'clip-path',
  'image-masking': 'image-masking',
  'video-masking': 'video-masking',
  'hover-cards': 'hover-cards',
  'product-cards': 'product-cards',
  'gradient-border': 'gradient-border',
  'spotlight-cards': 'spotlight-cards',
  'timeline-animation': 'timeline-animation',
  'scroll-animation': 'scroll-animation',
  'scroll-text': 'scroll-text',
  'scroll-text-marquee': 'scroll-text-marquee',
  'randomized-text-effect': 'randomized-text-effect',
  'image-mousetrail': 'image-mousetrail',
  'image-reveal': 'image-reveal',
  'progressive-carousel': 'progressive-carousel',
  blocks: 'blocks',
  'animated-beam': 'animated-beam',
  dialog: 'dialog',
  'media-modal': 'media-modal',
  'linear-modal': 'linear-modal',
  'gallery-modal': 'gallery-modal',
  'responsive-modal': 'responsive-modal',
  'directional-drawer': 'directional-drawer',
  'motion-drawer': 'motion-drawer',
  'right-motion-drawer': 'right-motion-drawer',
  'horizontal-scroll': 'horizontal-scroll',
  'stacking-card': 'stacking-card',
  'smooth-scroll': 'smooth-scroll',
  'sticky-scroll': 'sticky-scroll',
  tabs: 'tabs',
  'image-tabs': 'image-tabs',
  'magnified-doc': 'magnified-doc',
  sparkles: 'sparkles',
  'sparkles-title': 'sparkles-title',
  carousel: 'carousel',
  'framer-carousel': 'framer-carousel',
  accordion: 'accordion',
  faqs: 'faqs',
  'image-accordions': 'image-accordions',
  grid: 'grid',
  'masonary-grid': 'masonary-grid',
  marquee: 'marquee',
  'infinity-brand': 'infinity-brand',
} as const;

export const COMPONENT_KEYS = {
  // Default category
  LIQUID_GLASS_SIDEBAR_MENU: 'liquid-glass-sidebar-menu',
  LIQUID_GLASS_MOBILE_ICONS: 'liquid-glass-mobile-icons',
  LIQUID_GLASS_WEATHER: 'liquid-glass-weather',
  LIQUID_GLASS_NOTIFICATION: 'liquid-glass-notification',
  DRAG_ITEMS: 'drag-items',
  CARD_GLOBE_DEFAULT: 'card-globe-default',
  CARD_GLOBE_WHITE: 'card-globe-white',
  SPARKLES_GLOBE: 'sparkles-globe',
  ANIMATED_LOGO_FOOTER: 'animated-logo-footer',
  HOVER_FOOTER: 'hover-footer',
  BUTTON_BACKGROUND_SHINE: 'button-background-shine',
  BUTTON_BACKGROUND_SPOTLIGHT: 'button-background-spotlight',
  BUTTON_HOVER_ACTIVE: 'button-hover-active',
  BUTTON_HOVER_2: 'button-hover-2',
  BUTTON_HOVER_3: 'button-hover-3',
  BUTTON_HOVER_4: 'button-hover-4',
  BUTTON_HOVER_5: 'button-hover-5',
  BUTTON_HOVER_6: 'button-hover-6',
  BUTTON_HOVER_7: 'button-hover-7',
  BUTTON_HOVER_8: 'button-hover-8',
  BUTTON_HOVER_9: 'button-hover-9',
  BUTTON_HOVER_10: 'button-hover-10',
  BUTTON_HOVER_11: 'button-hover-11',
  BUTTON_HOVER_12: 'button-hover-12',
  BUTTON_HOVER_13: 'button-hover-13',
  BUTTON_HOVER_14: 'button-hover-14',
  BUTTON_ROTATING_GRADIENT: 'button-rotating-gradient',
  CREATIVE_BUTTON_1: 'creative-button-1',
  CREATIVE_BUTTON_2: 'creative-button-2',
  NOISE_EFFECT: 'noise-effect',
  BUYME_ACOFFEE: 'buyme-acoffee',

  // ThreeJS category
  IMG_RIPPLE_EFFECT: 'img-ripple-effect',
  SINGLE_IMG_RIPPLE_EFFECT: 'single-img-ripple-effect',
  R3F_BLOB: 'r3f-blob',
  MESH_SHADERGRADIENT: 'mesh-shadergradient',
  MESH_GRADIENT_BACKGROUND3: 'mesh-gradient-background3',
  MESH_GRADIENT_BACKGROUND2: 'mesh-gradient-background2',
  MESH_GRADIENT_BACKGROUND: 'mesh-gradient-background',

  // Accordion category
  GRID_LAYOUT_ACCORDION: 'grid-layout-accordion',
  SINGLE_LAYOUT_ACCORDION: 'single-layout-accordion',
  MULTI_LAYOUT_ACCORDION: 'multi-layout-accordion',
  FAQ_ACCORDION: 'faq-accordion',
  IMAGE_HOVER_ACCORDION: 'image-hover-accordion',
  TAILWIND_IMAGE_ACCORDION: 'tailwind-image-accordion',

  // Form category
  PHONE_INPUT_DEFAULT: 'phone-input-default',
  DUAL_RANGE_SLIDER: 'dual-range-slider',
  STATIC_RANGE_SLIDER: 'static-range-slider',
  POSITION_RANGE_SLIDER: 'position-range-slider',
  SHOWHIDE_PASS: 'showhide-pass',
  PASS_STRENGTHINDICATOR: 'pass-strengthindicator',
  PASS_STRENGTH_DOTTED_INDICATOR: 'pass-strength-dotted-indicator',
  PASS_STRENGTH_HOVER_INDICATOR: 'pass-strength-hover-indicator',
  PASS_STRENGTH_INLINE_INDICATOR: 'pass-strength-inline-indicator',
  CONFIRM_PASS_CHECK: 'confirm-pass-check',
  DATETIME_PICKER_DEFAULT: 'datetime-picke-default',
  TIME_PICKER: 'time-picker',
  DATE_PICKER: 'date-picker',
  TAGS_INPUT: 'tags-input',
  TAGSEDIT_FALSE: 'tagsedit-false',
  MULTI_SELECTOR_DEFAULT: 'multi-selector-default',
  FILE_UPLOAD_DEFAULT: 'file-upload-default',
  IMGPREVIEW_DROPZONE: 'imgpreview-dropzone',
  CHAT_FORM_DROPZONE: 'chat-form-dropzone',

  // Sparkles category
  SPARKLES_SECTION: 'sparkles-section',
  SPARKLES_BRANDING: 'sparkles-branding',
  SPARKLES_TITLE: 'sparkles-title',
  SPARKLES_TITLE2: 'sparkles-title2',
  SPARKLES_TITLE3: 'sparkles-title3',
  SPARKLES_TITLE4: 'sparkles-title4',

  // Swapy category
  DEFAULT_SWAPY: 'default-swapy',
  OPACITY_SWAPY: 'opacity-swapy',
  SWAPY_HANDLE: 'swapy-handle',
  SWAPY_WITHOUT_COMPONENTS: 'swapy-without-components',

  // ColorPicker category
  DEFAULT_COLOR_PICKER: 'default-color-picker',
  RAWS_COLOR_PICKER: 'raws-color-picker',

  // Carousel category
  DEFAULT_SLIDER: 'default-slider',
  ALIGN_SLIDER: 'align-slider',
  CLASSNAME_SLIDER: 'classname-slider',
  NUMBER_SLIDER: 'number-slider',
  SCALE_SLIDER: 'scale-slider',
  THUMBNAIL_SLIDER: 'thumbnail-slider',
  VERTICAL_SLIDER: 'vertical-slider',
  VERTICAL_THUMBNAIL_AUTOSTART_SLIDER: 'vertical-thumbnail-autostart-slider',
  VERTICAL_THUMBNAIL_SLIDER: 'vertical-thumbnail-slider',
  AUTOSTART_SLIDER: 'autostart-slider',
  AUTOSCROLL_SLIDER: 'autoscroll-slider',
  HORIZONTAL_PROGRESSIVE_CAROUSEL: 'horizontal-progressive-carousel',
  VERTICAL_PROGRESSIVE_CAROUSEL: 'vertical-progressive-carousel',
  FRAMER_DRAG_SLIDING_CAROUSEL: 'framer-drag-sliding-carousel',
  FRAMER_CAROUSEL_1: 'framer-carousel-1',
  FRAMER_NORMAL_CAROUSEL: 'framer-normal-carousel',
  FRAMER_DRAGGABLE_CAROUSEL: 'framer-draggable-carousel',
  FRAMER_AUTOPLAY_CAROUSEL: 'framer-autoplay-carousel',
  FRAMER_MULTI_CAROUSEL: 'framer-multi-carousel',
  FRAMER_THUMBNAILS: 'framer-thumbnails',
  FRAMER_MOVEABLE_THUMBNAILS: 'framer-moveable-thumbnails',

  // Creative category
  IMAGE_REVEAL: 'image-reveal',
  IMAGE_REVEAL2: 'image-reveal2',
  UILAYOUTS_GITHUB_BUTTON: 'uilayouts-github-button',
  LIQUID_GRADIENT: 'liquid-gradient',
  LIQUID_BUTTON: 'liquid-button',
  BLUR_VIGNETTE_VIDEO: 'blur-vignette-video',
  BLUR_VIGNETTE_IMG: 'blur-vignette-img',
  BLUR_VIGNETTE_CARD: 'blur-vignette-card',
  ANIMATED_BEAM_DEFAULT: 'animated-beam-default',
  ANIMATED_BEAM_BIDIRECTIONAL: 'animated-beam-bidirectional',
  ANIMATED_BEAM_UNIDIRECTIONAL: 'animated-beam-unidirectional',
  ANIMATED_BEAM_MULTIPLE_INPUT: 'animated-beam-multiple-input',
  ANIMATED_BEAM_MULTIPLE_OUTPUT: 'animated-beam-multiple-output',
  BG_BLOCKS_ONE: 'bg-blocks-one',
  MOTION_NUMBER_INPUT: 'motion-number-input',
  NUMBER_FLOW_TRADING: 'number-flow-trading',
  MOTION_NUMBER_SLIDER: 'motion-number-slider',
  MOTION_NUMBER_UPVOTES: 'motion-number-upvotes',
  IMAGE_MOUSETRAIL_DEFAULT: 'image-mousetrail-default',
  IMAGE_MOUSETRAIL_SMALL: 'image-mousetrail-small',
  IMAGE_MOUSETRAIL_DISAPPEAR: 'image-mousetrail-disappear',
  IMAGE_MOUSETRAIL_WITHOUT_COMPONENT: 'image-mousetrail-without-component',

  // Drawer category
  RESPONSIVE_HEADER_DEFAULT: 'responsive-header-default',
  DIRECTIONAL_DRAWER_DEFAULT: 'directional-drawer-default',
  LEFT_DIRECTIONAL_DRAWER: 'left-directional-drawer',
  TOP_DIRECTIONAL_DRAWER: 'top-directional-drawer',
  BOTTOM_DIRECTIONAL_DRAWER: 'bottom-directional-drawer',
  NESTED_DRAWER: 'nested-drawer',
  MOTION_DRAWER_DEFAULT: 'motion-drawer-default',
  RIGHT_MOTION_DRAWER: 'right-motion-drawer',

  // Modal/Dialog category
  DIALOG_DEFAULT: 'dialog-default',
  RESPONSIVE_MODAL_DEFAULT: 'responsive-modal-default',
  MEDIA_MODAL_DEFAULT: 'media-modal-default',
  IMAGEMODALS: 'imagemodals',
  LINEAR_MODAL_DEFAULT: 'linear-modal-default',
  LINEAR_MODAL_STANDALONE: 'linear-modal-standalone',
  LINEAR_MODAL_CENTER_CONTENT: 'linear-modal-center-content',
  GALLERY_MODAL_ACCORDION: 'gallery-modal-accordion',
  GALLERY_MODAL_SLIDER: 'gallery-modal-slider',
  GALLERY_MODAL_UNSPLASH: 'gallery-modal-unsplash',

  // Animation category
  SCROLL_ANIMATION_DEFAULT: 'scroll-animation-default',
  SCROLL_ANIMATION_REPEAT: 'scroll-animation-repeat',
  SCROLL_ANIMATION_TEXT: 'scroll-animation-text',
  TIMELINE_ANIMATION_DEFAULT: 'timeline-animation-default',

  // TextAnimation category
  TEXT_SCROLL_ANIMATION: 'text-scroll-animation',
  SCROLL_TEXT_MARQUEE_UNIDIRECTIONAL: 'scroll-text-marquee-unidirectional',
  SCROLL_TEXT_MARQUEE_BIDIRECTIONAL: 'scroll-text-marquee-bidirectional',
  RANDOMIZED_TEXT_UNVEIL: 'randomized-text-unveil',

  // Scroll category
  HORIZONTALSCROLL: 'horizontalscroll',
  STACKING_CARD: 'stacking-card',
  CSS_CARD_STACKING: 'css-card-stacking',
  CSS_IMAGE_STACKING: 'css-image-stacking',
  SMOOTH_SCROLL: 'smooth-scroll',
  STICKY_SCROLL_SECTION: 'sticky-scroll-section',
  STICKY_GALLERY: 'sticky-gallery',
  STICKY_HERO_SECTION: 'sticky-hero-section',
  FRAMERHORIZONTALSCROLL: 'framerhorizontalscroll',

  // Grid category
  BOXGRID: 'boxgrid',
  CONDITIONGRID: 'conditionGrid',
  NORMALGRID: 'normalGrid',
  UNSPLASHGRID: 'unsplashGrid',

  // Marquee category
  INFINTYBAND: 'infintyband',
  DEFAULT_MARQUEE: 'default-marquee',
  VERTICLE_MARQUEE: 'verticle-marquee',
  LOGOS_MARQUEE: 'logos-marquee',
  MARQUEE_3D: '3d-marquee',

  // Clip-Path category
  CREATIVE_CLIPPATH: 'creative-clippath',
  CORPORATE_CLIPPATH: 'corporate-clippath',
  SYMBOLIC_CLIPPATH: 'symbolic-clippath',
  CREATIVE_MASK_CLIPPATH: 'creative-mask-clippath',
  WATERSPLASH_CLIPPATH: 'watersplash-clippath',
  CREATIVE_IMAGEMASKING: 'creative-imagemasking',
  ANIMAL_IMAGEMASKING: 'animal-imagemasking',
  WATERSPLASH_IMAGEMASKING: 'watersplash-imagemasking',
  CENTER_IMAGEMASKING: 'center-imagemasking',
  FIXEDBG_IMAGEMASKING: 'fixedbg-imagemasking',
  CREATIVE_VIDEOMASKING: 'creative-videomasking',
  SPLASHWATER_VIDEOMASKING: 'splashwater-videomasking',
  TEXTOVERLAY_VIDEOMASKING: 'textoverlay-videomasking',
  HEXAGON_VIDEOMASKING: 'hexagon-videomasking',
  HEXAGON2_VIDEOMASKING: 'hexagon2-videomasking',

  // Card category
  GRADIENT_BORDER: 'gradient-border',
  STRIPECARD: 'stripecard',
  STRIPECARD2: 'stripecard2',
  HOVERCARD4: 'hovercard4',
  HOVERCARD3: 'hovercard3',
  HOVERCARD2: 'hovercard2',
  HOVERCARD1: 'hovercard1',
  CREATIVE_HOVER_CARD: 'creative-hover-card',
  PRODUCTCARD1: 'productcard1',
  PRODUCTCARD2: 'productcard2',
  PRODUCTCARD3: 'productcard3',
  PRODUCTCARD4: 'productcard4',
  PRODUCTCARD5: 'productcard5',
  PRODUCTCARD6: 'productcard6',
  SPOTLIGHT_CARD1: 'spotlight-card1',
  SPOTLIGHT_CARD2: 'spotlight-card2',
  SPOTLIGHT_CARD3: 'spotlight-card3',
  SPOTLIGHT_CARD4: 'spotlight-card4',

  // Tabs category
  MAINTABS: 'maintabs',
  CREATIVE_TAB: 'creative-tab',
  REGISTER_TAB: 'register-tab',
  MAGNIFIED_TAB: 'magnified-tab',
  IMAGE_TAB1: 'image-tab1',
  IMAGE_TAB2: 'image-tab2',
  IMAGE_TAB_STANDALONE: 'image-tab-standalone',
} as const;
