export const DOCS_CATEGORY = {
  Default: 'Default',
  ThreeJS: 'ThreeJS',
  Accordion: 'Accordion',
  Form: 'Form',
  Sparkles: 'Sparkles',
  Swapy: 'Swapy',
  ColorPicker: 'ColorPicker',
  Carousel: 'Carousel',
  Creative: 'Creative',
  'Modal/Drawer': 'Modal/Drawer',
  Animation: 'Animation',
  TextAnimation: 'TextAnimation',
  Scroll: 'Scroll',
  Grid: 'Grid',
  Marquee: 'Marquee',
  'Clip-Path': 'Clip-Path',
  Card: 'Card',
  Tabs: 'Tabs',
} as const;
