import { getMinimalBlocksBySection } from '@/blocks-docs';
import BlocksHomeClient from '@/components/website/blocks-components/blocks-page';
import { siteConfig } from '@/lib/utils';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: {
    default: 'Blocks | UI-Layouts',
    template: `%s - ${siteConfig.blocksName}`,
  },
  metadataBase: new URL(siteConfig.url),
  description: siteConfig.blocksDescription,
  keywords: [
    'React blocks',
    'Next.js blocks',
    'UI blocks',
    'Tailwind CSS blocks',
    'shadcn ui blocks',
    'React components',
    'Next.js components',
    'UI components',
    'web components',
    'frontend components',
    'React UI kit',
    'Next.js UI kit',
    'Tailwind CSS components',
    'shadcn components',
    'Framer Motion',
    'React animations',
    'web animations',
    'scroll animations',
    'parallax effects',
    'interactive components',
    'responsive design',
    'modern UI',
    'landing page blocks',
    'hero sections',
    'feature sections',
    'about sections',
    'footer components',
    'header components',
    'card components',
    'pricing sections',
    'team sections',
    'testimonials',
    'contact forms',
    'navigation components',
    'sidebar components',
    'carousel components',
    'slider components',
    'modal components',
    'dropdown components',
    'accordion components',
    'tabs components',
    'button components',
    'form components',
    'layout components',
    'grid layouts',
    'flex layouts',
    'dark mode',
    'light mode',
    'responsive design',
    'mobile first',
    'accessibility',
    'WCAG compliant',
    'SEO friendly',
    'performance optimized',
    'clean code',
    'modern React',
    'Next.js 15',
    'React 19',
    'TypeScript components',
    'JavaScript components',
    'open source',
    'free components',
    'MIT license',
    'copy paste',
    'ready to use',
    'production ready',
    'enterprise ready',
    'startup UI',
    'SaaS UI',
    'dashboard blocks',
    'portfolio blocks',
    'blog components',
    'ecommerce components',
    'marketing components',
    'business website',
    'agency website',
    'portfolio website',
    'personal website',
    'startup website',
    'web development',
    'frontend development',
    'UI design',
    'UX design',
    'component library',
    'design system',
    'UI framework',
    'CSS framework',
    'React framework',
    'Next.js framework',
    'modern web development',
    'web design',
    'interface design',
    'user interface',
    'user experience',
    'web components',
    'custom components',
    'reusable components',
    'modular design',
    'component architecture',
    'scalable UI',
    'maintainable code',
    'best practices',
    'industry standards',
    'professional UI',
    'high quality components',
    'premium components',
    'free UI kit',
    'component marketplace',
    'UI templates',
    'web templates',
    'React templates',
    'Next.js templates',
    'Tailwind templates',
    'shadcn templates',
    'UI blocks',
    'section blocks',
    'page sections',
    'website sections',
    'landing page sections',
    'pre-built sections',
    'UI sections',
    'web sections',
    'component sections',
    'design blocks',
    'layout blocks',
    'content blocks',
    'feature blocks',
    'hero blocks',
    'CTA blocks',
    'testimonial blocks',
    'pricing blocks',
    'team blocks',
    'about blocks',
    'contact blocks',
    'footer blocks',
    'header blocks',
    'navigation blocks',
    'card blocks',
    'form blocks',
    'gallery blocks',
    'portfolio blocks',
    'blog blocks',
    'ecommerce blocks',
    'dashboard blocks',
    'admin blocks',
    'SaaS blocks',
    'startup blocks',
    'business blocks',
    'agency blocks',
    'creative blocks',
    'modern blocks',
    'minimal blocks',
    'clean blocks',
    'professional blocks',
    'corporate blocks',
    'enterprise blocks',
  ],
  authors: [
    {
      name: 'naymur rahman',
      url: 'https://naymur.com/',
    },
  ],
  creator: 'naymur',
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: siteConfig.blocksUrl,
    title: siteConfig.blocksName,
    description: siteConfig.blocksDescription,
    siteName: siteConfig.name,
    images: [
      {
        url: siteConfig.BlocksOgImage,
        width: 1200,
        height: 630,
        alt: siteConfig.blocksName,
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: siteConfig.blocksName,
    description: siteConfig.blocksDescription,
    images: [siteConfig.BlocksOgImage],
    creator: '@naymur_dev',
    site: '@naymur_dev',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'google-site-verification-code',
    yandex: 'yandex-verification-code',
    yahoo: 'yahoo-site-verification-code',
  },
  alternates: {
    canonical: siteConfig.blocksUrl,
    languages: {
      'en-US': siteConfig.blocksUrl,
      'en-GB': siteConfig.blocksUrl,
    },
  },
  icons: {
    icon: '/favicon.ico',
    shortcut: '/favicon-16x16.png',
    apple: '/apple-touch-icon.png',
  },
  manifest: `${siteConfig.url}/site.webmanifest`,
  other: {
    'theme-color': '#000000',
    'msapplication-TileColor': '#000000',
    'apple-mobile-web-app-title': 'UI-Layouts Blocks',
    'application-name': 'UI-Layouts Blocks',
    'msapplication-config': '/browserconfig.xml',
  },
  category: 'technology',
  classification: 'Web Development',
  referrer: 'origin-when-cross-origin',
};
export default function BlocksHome() {
  const blocksData = getMinimalBlocksBySection();
  return (
    <>
      <BlocksHomeClient blocksData={blocksData} />
    </>
  );
}
