type RawMarkdown = string | { default: string };

function unwrapMarkdown(markdown: RawMarkdown) {
  return typeof markdown === 'string' ? markdown : markdown.default;
}

const blockDesignDocuments: Record<string, RawMarkdown> = {
  'about-agency': require('../../../packages/blocks/src/about-section/about-agency/design.md?raw'),
  'about-architecture': require('../../../packages/blocks/src/about-section/about-architecture/design.md?raw'),
  'about-bento': require('../../../packages/blocks/src/about-section/about-bento/design.md?raw'),
  'about-business': require('../../../packages/blocks/src/about-section/about-business/design.md?raw'),
  'about-creative': require('../../../packages/blocks/src/about-section/about-creative/design.md?raw'),
  'about-ecommerse': require('../../../packages/blocks/src/about-section/about-ecommerse/design.md?raw'),
  'about-experience': require('../../../packages/blocks/src/about-section/about-experience/design.md?raw'),
  'about-me': require('../../../packages/blocks/src/about-section/about-me/design.md?raw'),
  'about-mission': require('../../../packages/blocks/src/about-section/about-mission/design.md?raw'),
  'about-sass': require('../../../packages/blocks/src/about-section/about-sass/design.md?raw'),
  'about-vision': require('../../../packages/blocks/src/about-section/about-vision/design.md?raw'),
  'about-whyus': require('../../../packages/blocks/src/about-section/about-whyus/design.md?raw'),
  'advanced-stats': require('../../../packages/blocks/src/stats-section/advanced-stats/index/design.md?raw'),
  'chat-interface-testimonial': require('../../../packages/blocks/src/testimonial-section/chat-interface/design.md?raw'),
  'creative-experience': require('../../../packages/blocks/src/experience-section/creative-experience/design.md?raw'),
  'customer-experience': require('../../../packages/blocks/src/experience-section/customer-experience/design.md?raw'),
  'faq-founder': require('../../../packages/blocks/src/faq-section/faq-founder/design.md?raw'),
  'faq-glass-card': require('../../../packages/blocks/src/faq-section/faq-glass-card/design.md?raw'),
  'faq-interactive-preview': require('../../../packages/blocks/src/faq-section/faq-interactive-preview/design.md?raw'),
  'faq-journey': require('../../../packages/blocks/src/faq-section/faq-journey/design.md?raw'),
  'faq-minimilastic': require('../../../packages/blocks/src/faq-section/faq-minimilastic/design.md?raw'),
  'faq-tabbed-explorer': require('../../../packages/blocks/src/faq-section/faq-tabbed-explorer/design.md?raw'),
  'feature-bento': require('../../../packages/blocks/src/feature-section/feature-bento/design.md?raw'),
  'feature-flow': require('../../../packages/blocks/src/feature-section/feature-flow/design.md?raw'),
  'feature-hero': require('../../../packages/blocks/src/feature-section/feature-hero/design.md?raw'),
  'feature-highlights': require('../../../packages/blocks/src/feature-section/feature-highlights/design.md?raw'),
  'feature-nature': require('../../../packages/blocks/src/feature-section/feature-nature/design.md?raw'),
  'feature-platform': require('../../../packages/blocks/src/feature-section/feature-platform/design.md?raw'),
  'feature-service': require('../../../packages/blocks/src/feature-section/feature-service/design.md?raw'),
  'feature-velocity': require('../../../packages/blocks/src/feature-section/feature-velocity/design.md?raw'),
  'footer-bento': require('../../../packages/blocks/src/footer-section/footer-bento/design.md?raw'),
  'footer-bold': require('../../../packages/blocks/src/footer-section/footer-bold/design.md?raw'),
  'footer-detailed': require('../../../packages/blocks/src/footer-section/footer-detailed/design.md?raw'),
  'footer-hero': require('../../../packages/blocks/src/footer-section/hero-footer/design.md?raw'),
  'footer-minimal': require('../../../packages/blocks/src/footer-section/footer-minimal/design.md?raw'),
  'footer-privilege': require('../../../packages/blocks/src/footer-section/footer-privilege/design.md?raw'),
  'footer-simple': require('../../../packages/blocks/src/footer-section/footer-simple/design.md?raw'),
  'growth-plans': require('../../../packages/blocks/src/pricing-section/growth-plans/design.md?raw'),
  'hero-ai-ecommerce': require('../../../packages/blocks/src/hero-section/hero-ai-ecommerce/design.md?raw'),
  'hero-ai-infrastructure': require('../../../packages/blocks/src/hero-section/hero-ai-infrastructure/design.md?raw'),
  'hero-ai-value-proposition': require('../../../packages/blocks/src/hero-section/hero-ai-value-proposition/design.md?raw'),
  'hero-digital-success': require('../../../packages/blocks/src/hero-section/hero-digital-success/design.md?raw'),
  'hero-financial': require('../../../packages/blocks/src/hero-section/hero-financial/design.md?raw'),
  'hero-share-app': require('../../../packages/blocks/src/hero-section/hero-share-app/design.md?raw'),
  'hero-social-app': require('../../../packages/blocks/src/hero-section/hero-social-app/design.md?raw'),
  'impact-experience': require('../../../packages/blocks/src/experience-section/impact-experience/design.md?raw'),
  'marque-testimonial': require('../../../packages/blocks/src/testimonial-section/marque-testimonial/design.md?raw'),
  'messenger-testimonial': require('../../../packages/blocks/src/testimonial-section/messenger-testimonial/design.md?raw'),
  'portfolio-experience': require('../../../packages/blocks/src/experience-section/portfolio-experience/design.md?raw'),
  'pricing-grow-business': require('../../../packages/blocks/src/pricing-section/grow-business/design.md?raw'),
  'pricing-overview': require('../../../packages/blocks/src/pricing-section/pricing-overview/design.md?raw'),
  'product-packs': require('../../../packages/blocks/src/pricing-section/product-packs/design.md?raw'),
  'spotlight-testimonial': require('../../../packages/blocks/src/testimonial-section/spotlight-testimonial/design.md?raw'),
  'stack-testimonial': require('../../../packages/blocks/src/testimonial-section/stack-testimonial/design.md?raw'),
  'startup-plans': require('../../../packages/blocks/src/pricing-section/startup-plans/design.md?raw'),
  'stats-banner': require('../../../packages/blocks/src/stats-section/stats-banner/design.md?raw'),
  'stats-bento': require('../../../packages/blocks/src/stats-section/stats-bento/design.md?raw'),
  'stats-bold': require('../../../packages/blocks/src/stats-section/stats-bold/design.md?raw'),
  'stats-details': require('../../../packages/blocks/src/stats-section/stats-details/design.md?raw'),
  'stats-minimal': require('../../../packages/blocks/src/stats-section/stats-minimal/design.md?raw'),
  'stats-section': require('../../../packages/blocks/src/stats-section/stats-section/design.md?raw'),
  'subscription-details': require('../../../packages/blocks/src/pricing-section/subscription-details/design.md?raw'),
  'team-classic': require('../../../packages/blocks/src/team-section/team-classic/design.md?raw'),
  'team-clippath': require('../../../packages/blocks/src/team-section/team-clippath/design.md?raw'),
  'team-expert': require('../../../packages/blocks/src/team-section/team-expert/design.md?raw'),
  'team-magic': require('../../../packages/blocks/src/team-section/team-magic/design.md?raw'),
  'team-modern': require('../../../packages/blocks/src/team-section/team-modern/design.md?raw'),
  'team-social': require('../../../packages/blocks/src/team-section/team-social/design.md?raw'),
  'team-synth': require('../../../packages/blocks/src/team-section/team-synth/design.md?raw'),
  'team-troops': require('../../../packages/blocks/src/team-section/team-troops/design.md?raw'),
  'team-vr': require('../../../packages/blocks/src/team-section/team-vr/design.md?raw'),
  'testimonial-basic': require('../../../packages/blocks/src/testimonial-section/testimonial-basic/design.md?raw'),
  'testimonial-carousel': require('../../../packages/blocks/src/testimonial-section/testimonial-carousel/design.md?raw'),
  'work-experience': require('../../../packages/blocks/src/experience-section/work-experience/design.md?raw'),
};

export function getBlockDesignMarkdown(id: string) {
  const document = blockDesignDocuments[id];
  if (!document) throw new Error(`Missing adjacent design document for block: ${id}`);
  return unwrapMarkdown(document);
}
