import { Faq1Exp } from './../../../packages/blocks/src/faq-section/FAQ-1/Faq1Exp';
import preview from '@/assets/preview/Preview';
import {
  StreamLineHero,
  NuetralHero,
  WorkflowAutomation,
  FlowSync,
  AgencyHero,
  AgencyNeutral,
  OrganizationHero,
  TeamIntegration,
} from '@repo/blocks';

import {
  FaqImage1,
  TeamIntegrationImg,
  AgencyHeroImg,
  OrganizationHeroImg,
  WorkflowAutomationImg,
  FlowsyncHeroImg,
  AgencyNeutralHeroImg,
  NuetralHerImg,
  StreamLineHeroImg,
} from '@repo/blocks/assets/index';

export const blocksDesign = [
  {
    id: 'hero-section',
    name: 'Hero Section',
    url: '/blocks/hero-section',
    des: 'Beautiful hero layouts to start your landing page.',
    imgclass: 'object-cover',
    textClass: 'text-white',
    imgSrc: FlowsyncHeroImg,
    tags: ['hero', 'landing', 'above-the-fold'],
    blocks: [
      {
        id: 'streamline-hero',
        name: 'Streamline Hero',
        des: 'A modern hero section with call-to-action and image.',
        imgSrc: StreamLineHeroImg,
        tags: ['hero', 'modern', 'cta', 'streamline'],
        componentSrc: StreamLineHero,
        filePath: [
          'packages/blocks/src/hero-section/stream-line.tsx',
          'packages/ui/src/cpu-architecture.tsx',
          'packages/ui/src/progressive-blur.tsx',
          'apps/ui-layout/components/ui/marquee.tsx',
          'apps/ui-layout/components/website/ui/banner.tsx',
        ],
      },
      {
        id: 'organization-hero',
        name: 'Organization Hero',
        des: 'A modern hero section with call-to-action and image.',
        imgSrc: OrganizationHeroImg,
        tags: ['hero', 'modern', 'cta', 'organization'],
        componentSrc: OrganizationHero,
        filePath: [
          'packages/blocks/src/hero-section/organization.tsx',
          'packages/ui/src/progressive-blur.tsx',
        ],
      },
      {
        id: 'neutral-hero',
        name: 'Neutral Hero',
        des: 'A modern hero section with call-to-action and image.',
        imgSrc: NuetralHerImg,
        tags: ['hero', 'modern', 'cta', 'neutral'],
        componentSrc: NuetralHero,
        filePath: [
          'packages/blocks/src/hero-section/neutral-hero.tsx',
          'packages/ui/src/neural-noise.tsx',
        ],
      },
      {
        id: 'workflow-automation',
        name: 'Workflow Automation',
        des: 'A modern hero section with call-to-action and image.',
        imgSrc: WorkflowAutomationImg,
        tags: ['hero', 'modern', 'cta', 'workflow-automation'],
        componentSrc: WorkflowAutomation,
        filePath: [
          'packages/blocks/src/hero-section/workflow-autmation.tsx',
          'packages/ui/src/verticle-bars.tsx',
        ],
      },
      {
        id: 'flowsync-hero',
        name: 'Flowsync Hero',
        des: 'A modern hero section with call-to-action and image.',
        imgSrc: FlowsyncHeroImg,
        tags: ['hero', 'modern', 'cta', 'flowsync-hero'],
        componentSrc: FlowSync,
        filePath: ['packages/blocks/src/hero-section/flowsync.tsx'],
      },
      {
        id: 'agency-hero',
        name: 'Agency Hero',
        des: 'A modern hero section with call-to-action and image.',
        imgSrc: AgencyHeroImg,
        tags: ['hero', 'modern', 'cta', 'agency-hero'],
        componentSrc: AgencyHero,
        filePath: [
          'packages/blocks/src/hero-section/agency.tsx',
          'packages/ui/src/liquid-glass.tsx',
          'packages/ui/src/progressive-blur.tsx',
          'packages/ui/src/animated-tooltip.tsx',
        ],
      },
      {
        id: 'agency-neutral-hero',
        name: 'Agency Neutral Hero',
        des: 'A modern hero section with call-to-action and image.',
        imgSrc: AgencyNeutralHeroImg,
        tags: ['hero', 'modern', 'cta', 'agency-neutral-hero'],
        componentSrc: AgencyNeutral,
        filePath: [
          'packages/blocks/src/hero-section/agency-neutral.tsx',
          'packages/ui/src/neural-noise.tsx',
          'packages/ui/src/liquid-glass.tsx',
          'packages/ui/src/progressive-blur.tsx',
          'packages/ui/src/animated-tooltip.tsx',
        ],
      },

      {
        id: 'team-integration',
        name: 'Team Integration',
        des: 'A modern hero section with call-to-action.',
        imgSrc: TeamIntegrationImg,
        tags: ['hero', 'modern', 'cta'],
        componentSrc: TeamIntegration,
        filePath: ['packages/blocks/src/hero-section/team-intergration.tsx'],
      },
    ],
  },
  {
    id: 'faq-section',
    name: 'FAQ Section',
    url: '/blocks/faq-section',
    des: 'Beautiful FAQ layouts to start your landing page.',
    imgclass: 'object-contain',
    textClass: 'text-primary',
    imgSrc: preview.faqs,
    tags: ['FAQ', 'landing', 'above-the-fold'],
    blocks: [
      {
        id: 'faq-section',
        name: 'FAQ Section',
        des: 'A modern FAAQ section .',
        imgSrc: FaqImage1,
        tags: ['FAQ', 'modern', 'above-the-fold'],
        componentSrc: Faq1Exp,
        filePath: ['packages/blocks/src/faq-section/FAQ-1/faq1.tsx'],
      },
    ],
  },
];
