export { HeroSections1 } from './hero-section1'
export * from './hero-section2'
export * from './hero-section3'
export * from './hero-section4'
export * from './hero-section5'
export * from './hero-section6'
export * from './AnimateHero'
